---
abstract: ~
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: kenhat
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Engine::PSGI: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::Authorization::Roles: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::DBIC: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::Session::Store::File: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.80033
  Catalyst::View::CSS::Minifier::XS: 0
  Catalyst::View::JavaScript::Minifier::XS: 0
  Catalyst::View::TT: 0
  Config::General: 0
  DBD::mysql: 0
  DBI: 0
  Data::Dumper: 0
  Date::Calc: 0
  File::Slurp::Unicode: 0
  JSON: 0
  Moose: 0
  MooseX::MarkAsMethods: 0
  MooseX::NonMoose: 0
  Template: 0
  namespace::autoclean: 0
version: 0.01
