package kenhat::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'kenhat::Schema::DB',
    
    connect_info => {
        dsn => 'dbi:mysql:kenhat',
        user => 'kenhat',
        password => 'oudekerk',
    }
);

=head1 NAME

kenhat::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<kenhat>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<kenhat::Schema::DB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

kenhat

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
